[tool.poetry]
name = "pybmc"
version = "0.1.0"
description = "A package for Bayesian model combination"
authors = ["Kyle Godbey <pybmc@ascsn.net>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.0.0"
scipy = "^1.15.0"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.3"
mkdocs-material = "^8.0.0"
mkdocstrings = "^0.18.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4", "numpy"]
build-backend = "setuptools.build_meta"